site_name: My Markdown & GitHub Journey

nav:
  - Introduction: index.md
  - Learn Markdown:
      - Basics Part 01: markdown-basics.md
      - Basics Part 02: markdown-basics-02.md
      - Advanced: markdown-advanced.md
  - MkDocs & GitHub:
      - Create site with MkDocs: mkdocs.md
      - Deploy with GitHub Pages: github-pages.md
      - Workflow GitHub Actions: github-actions.md

theme:
  name: material


