site_name: My Markdown & GitHub Journey

nav:
  - Introduction: index.md
  - Learn Markdown:
      - Basic: markdown-basics.md
  - MkDocs & GitHub:
      - Create site with MkDocs: mkdocs.md
      - Deploy with GitHub Pages: github-pages.md
      - Workflow GitHub Actions: github-actions.md

theme:
  name: material


