name: Deploy MkDocs site

permissions:
  contents: write    # Quan trọng: cho phép push

on:
  push:
    branches: [main]   # Hoặc 'master' nếu repo bạn dùng nhánh đó

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --clean --verbose
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
